### ISSUE TITLE
Moving variable to a different file

### ISSUE THREAD

**Issue by ghost** [ElliotEKJ/Ditto-Photoshop-Extension#1]
Hi I love the extension but I thought I could just copy the ditto layers to another file and load them but that doesn't seem to work.

I wanted to create variables for all the colors I am using in a design so I could easily change them accross the elements using them. I have a different psd for each main screen and I didn't want to set up the variables in each file. I realize I will have to manually open each file and change the variable there.

**Comment by elliotekj** [comment]
Hey @artdog,

To reuse variables in a separate file, just duplicate over the `dittoVariables` folder and click “Load Variables” (make sure there isn’t already a different variables folder before doing so). Your layers will automatically be refreshed with the latest styles.

Hope that helps.

**Comment by ghost** [comment]
I tried that and it didn't work. I will try to post a screen shot of what I
got.

**Comment by ghost** [comment]
I've taken screen shots. Steps:
I added variables to the first file and all seemed to work fine. I opened a second psd and copied the dittoVariables folder to the new file by selecting it in the layers panel then dragging on the main screen and dropping onto another tab containing a different file.
Clicked the load variables button. I get two variables as "undefined"
![ditto-file-1](https://cloud.githubusercontent.com/assets/49877/8742103/a4dc2d26-2c59-11e5-95a3-2873395bc297.png)
![ditto-file-2](https://cloud.githubusercontent.com/assets/49877/8742106/a6a4b8bc-2c59-11e5-8635-30dae043a3cd.png)

**Comment by elliotekj** [comment]
Hmm, ok. Thanks for the screenshots—I’m looking into this and will release a fix as soon as possible.

**Comment by oryan** [comment]
@artdog one thing you could do for now is use the new Artboard feature. Keep all those screens and variables in one psd. My team and I have been using it for the last few weeks and it's pretty awesome.

https://www.youtube.com/watch?v=qkgsGhwG7rI

**Comment by elliotekj** [comment]
Thanks for contributing @oryan (and for using Ditto).

Just to keep this thread up to date a little, I’ve narrowed down the part that’s causing the error. I just need to find a few hours to sit down and fix it now.

**Comment by elliotekj** [comment]
This is fixed and will be out in an update later today.

**Comment by elliotekj** [comment]
Fixed in 1.1. [Download →](http://casualnotebook.com/ditto)
