### ISSUE TITLE
Clicking "clear list" causes undismissable alert

### ISSUE THREAD

**Issue by ghost** [ElliotEKJ/Ditto-Photoshop-Extension#2]
Alert window cannot be dismissed. Photoshop must be force quit.
![image 1](https://cloud.githubusercontent.com/assets/49877/8726919/dc1eeb78-2bd4-11e5-89d4-2efbdfdae969.png)

**Comment by elliotekj** [comment]
Oh, sorry about that! It’s dismissible on OS X. I’ll fix it in the next update.

**Comment by elliotekj** [comment]
This is fixed and will be out in an update later today.

**Comment by elliotekj** [comment]
Fixed in 1.1. [Download →](http://casualnotebook.com/ditto)
