### ISSUE TITLE
Unable to install script

### ISSUE THREAD

**Issue by oryan** [ElliotEKJ/Ditto-Photoshop-Extension#6]
Running the script as directed in the readme leads to an error.

**System Info**
- OSX 10.10
- PS CC2015

**Steps:**
1.  load script from file menu in photoshop
2.   click ok to run script.
3.  error message. (The error says to create a directory manually)
4.  create directory in location specified.
5.  run script again.
6.  same result

![image](https://cloud.githubusercontent.com/assets/3709153/8784783/4f2ee0e0-2ed8-11e5-8ec1-52527546cdc9.png)

**Comment by elliotekj** [comment]
Hey @oryan,

Sorry about that. Here are the steps to install manually:
1. In the folder downloaded from my site, copy the `HTML` folder located within the `ASSETS` folder.
2. In the same extensions folder you’ve posted a screenshot of above (`~/Library/Application Support/Adobe/CEP/exetensions` for anyone else reading this), delete `com.casualnotebook.variables` then paste the `HTML` folder.
3. Rename the `HTML` folder to `com.casualnotebook.variables`
4. Restart Photoshop.

That should do the trick, let me know if you run into any other difficulties.

---

Note to self: Update README.md with manual install instructions.

**Comment by oryan** [comment]
Ah, that did the trick.

Thanks for the help. I'm really excited to start using this.

**Comment by elliotekj** [comment]
Added in 1.1. [Download →](http://casualnotebook.com/ditto)
