### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by skynebula** [ElliotEKJ/Ditto-Photoshop-Extension#7]
Hi!
Impossible for me to install your plugin.
When I open the .jsx file and press "Play", I have this error message.

<img width="958" alt="ditto_bug" src="https://cloud.githubusercontent.com/assets/669147/8800763/b4520398-2fb5-11e5-8b6c-be8d4a191f82.png">

I have Adobe Photoshop CC 2015.0.0 on OS X 10.10.4

**Comment by elliotekj** [comment]
Hey @skynebula,

In the README.md file you’ll find instructions on how to install it. In Photoshop, go to “File” → “Scripts”, select “Browse...” and choose the installer.jsx file from there.

**Comment by skynebula** [comment]
Great! Thank you @ElliotEKJ! I did not see that you changed the README.md since the previous version...
All good for now!
And thank you for this great idea!
